#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : qdmr
Version  : 0.12.1
Release  : 5
URL      : https://github.com/hmatuschek/qdmr/archive/v0.12.1/qdmr-0.12.1.tar.gz
Source0  : https://github.com/hmatuschek/qdmr/archive/v0.12.1/qdmr-0.12.1.tar.gz
Summary  : Graphical code-plug programming tool for DMR radios
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0-or-later
Requires: qdmr-bin = %{version}-%{release}
Requires: qdmr-data = %{version}-%{release}
Requires: qdmr-lib = %{version}-%{release}
Requires: qdmr-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : qtbase-dev
BuildRequires : qtlocation-dev
BuildRequires : qtserialport-dev
BuildRequires : qttools-dev
BuildRequires : yaml-cpp-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-compile-errors.patch

%description
qdmr is a Qt5 application to program DMR radios. DMR is a digital modulation
standard used in amateur and commercial radio. To this end, qdmr is an
alternative codeplug programming software (CPS) that supports several radios
across several manufacturers.

Currently supported devices are:
 * Radioddity/Baofeng RD-5R, GD-73, GD-77
 * TYT MD-380, MD-390, MD-UV380, MD-UV390, MD-2017
 * Retevis RT8, RT3S, RT82
 * Open GD77 firmware (GD77, RD-5R & DM-1801)
 * AnyTone AT-D868UVE, AT-D878UV, AT-878UVII, AT-D578UV
 * BTech DMR-6X2, DM-1701, DR-1801UV

%package bin
Summary: bin components for the qdmr package.
Group: Binaries
Requires: qdmr-data = %{version}-%{release}
Requires: qdmr-license = %{version}-%{release}

%description bin
bin components for the qdmr package.


%package data
Summary: data components for the qdmr package.
Group: Data

%description data
data components for the qdmr package.


%package dev
Summary: dev components for the qdmr package.
Group: Development
Requires: qdmr-lib = %{version}-%{release}
Requires: qdmr-bin = %{version}-%{release}
Requires: qdmr-data = %{version}-%{release}
Provides: qdmr-devel = %{version}-%{release}
Requires: qdmr = %{version}-%{release}

%description dev
dev components for the qdmr package.


%package lib
Summary: lib components for the qdmr package.
Group: Libraries
Requires: qdmr-data = %{version}-%{release}
Requires: qdmr-license = %{version}-%{release}

%description lib
lib components for the qdmr package.


%package license
Summary: license components for the qdmr package.
Group: Default

%description license
license components for the qdmr package.


%prep
%setup -q -n qdmr-0.12.1
cd %{_builddir}/qdmr-0.12.1
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738350623
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738350623
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qdmr
cp %{_builddir}/qdmr-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/qdmr/31a3d460bb3c7d98845187c716a30db81c44b615 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/OFF/99-qdmr.rules

%files bin
%defattr(-,root,root,-)
/usr/bin/dmrconf
/usr/bin/qdmr

%files data
%defattr(-,root,root,-)
/usr/share/applications/qdmr.desktop
/usr/share/icons/hicolor/32x32/qdmr.png
/usr/share/icons/hicolor/48x48/qdmr.png
/usr/share/icons/hicolor/64x64/qdmr.png
/usr/share/icons/hicolor/72x72/qdmr.png
/usr/share/icons/hicolor/96x96/qdmr.png
/usr/share/locale/de/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/en_US/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/fr/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/it/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/nl/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/pl/LC_MESSAGES/qdmr_qt.qm
/usr/share/locale/sv/LC_MESSAGES/qdmr_qt.qm

%files dev
%defattr(-,root,root,-)
/usr/include/libdmrconf/addressmap.hh
/usr/include/libdmrconf/anytone_codeplug.hh
/usr/include/libdmrconf/anytone_extension.hh
/usr/include/libdmrconf/anytone_interface.hh
/usr/include/libdmrconf/anytone_limits.hh
/usr/include/libdmrconf/anytone_radio.hh
/usr/include/libdmrconf/auctus_a6_interface.hh
/usr/include/libdmrconf/c7000device.hh
/usr/include/libdmrconf/callsigndb.hh
/usr/include/libdmrconf/channel.hh
/usr/include/libdmrconf/chirpformat.hh
/usr/include/libdmrconf/codeplug.hh
/usr/include/libdmrconf/commercial_extension.hh
/usr/include/libdmrconf/config.h
/usr/include/libdmrconf/config.hh
/usr/include/libdmrconf/configcopyvisitor.hh
/usr/include/libdmrconf/configlabelingvisitor.hh
/usr/include/libdmrconf/configmergevisitor.hh
/usr/include/libdmrconf/configobject.hh
/usr/include/libdmrconf/configreference.hh
/usr/include/libdmrconf/contact.hh
/usr/include/libdmrconf/crc32.hh
/usr/include/libdmrconf/csvreader.hh
/usr/include/libdmrconf/d578uv.hh
/usr/include/libdmrconf/d578uv_codeplug.hh
/usr/include/libdmrconf/d578uv_limits.hh
/usr/include/libdmrconf/d868uv.hh
/usr/include/libdmrconf/d868uv_callsigndb.hh
/usr/include/libdmrconf/d868uv_codeplug.hh
/usr/include/libdmrconf/d868uv_limits.hh
/usr/include/libdmrconf/d878uv.hh
/usr/include/libdmrconf/d878uv2.hh
/usr/include/libdmrconf/d878uv2_callsigndb.hh
/usr/include/libdmrconf/d878uv2_codeplug.hh
/usr/include/libdmrconf/d878uv2_limits.hh
/usr/include/libdmrconf/d878uv_codeplug.hh
/usr/include/libdmrconf/d878uv_limits.hh
/usr/include/libdmrconf/dfu_libusb.hh
/usr/include/libdmrconf/dfufile.hh
/usr/include/libdmrconf/dm1701.hh
/usr/include/libdmrconf/dm1701_callsigndb.hh
/usr/include/libdmrconf/dm1701_codeplug.hh
/usr/include/libdmrconf/dm1701_filereader.hh
/usr/include/libdmrconf/dm1701_limits.hh
/usr/include/libdmrconf/dmr6x2uv.hh
/usr/include/libdmrconf/dmr6x2uv_codeplug.hh
/usr/include/libdmrconf/dmr6x2uv_limits.hh
/usr/include/libdmrconf/dr1801uv.hh
/usr/include/libdmrconf/dr1801uv_codeplug.hh
/usr/include/libdmrconf/dr1801uv_filereader.hh
/usr/include/libdmrconf/dr1801uv_interface.hh
/usr/include/libdmrconf/dr1801uv_limits.hh
/usr/include/libdmrconf/dummyfilereader.hh
/usr/include/libdmrconf/encryptionextension.hh
/usr/include/libdmrconf/errorstack.hh
/usr/include/libdmrconf/frequency.hh
/usr/include/libdmrconf/gd73.hh
/usr/include/libdmrconf/gd73_codeplug.hh
/usr/include/libdmrconf/gd73_filereader.hh
/usr/include/libdmrconf/gd73_interface.hh
/usr/include/libdmrconf/gd73_limits.hh
/usr/include/libdmrconf/gd77.hh
/usr/include/libdmrconf/gd77_callsigndb.hh
/usr/include/libdmrconf/gd77_codeplug.hh
/usr/include/libdmrconf/gd77_filereader.hh
/usr/include/libdmrconf/gd77_limits.hh
/usr/include/libdmrconf/gpssystem.hh
/usr/include/libdmrconf/hid_libusb.hh
/usr/include/libdmrconf/intermediaterepresentation.hh
/usr/include/libdmrconf/interval.hh
/usr/include/libdmrconf/libdmrconf.hh
/usr/include/libdmrconf/logger.hh
/usr/include/libdmrconf/md2017.hh
/usr/include/libdmrconf/md2017_callsigndb.hh
/usr/include/libdmrconf/md2017_codeplug.hh
/usr/include/libdmrconf/md2017_filereader.hh
/usr/include/libdmrconf/md2017_limits.hh
/usr/include/libdmrconf/md390.hh
/usr/include/libdmrconf/md390_codeplug.hh
/usr/include/libdmrconf/md390_filereader.hh
/usr/include/libdmrconf/md390_limits.hh
/usr/include/libdmrconf/melody.hh
/usr/include/libdmrconf/opengd77.hh
/usr/include/libdmrconf/opengd77_callsigndb.hh
/usr/include/libdmrconf/opengd77_codeplug.hh
/usr/include/libdmrconf/opengd77_extension.hh
/usr/include/libdmrconf/opengd77_interface.hh
/usr/include/libdmrconf/opengd77_limits.hh
/usr/include/libdmrconf/opengd77base.hh
/usr/include/libdmrconf/opengd77base_callsigndb.hh
/usr/include/libdmrconf/opengd77base_codeplug.hh
/usr/include/libdmrconf/openrtx.hh
/usr/include/libdmrconf/openrtx_codeplug.hh
/usr/include/libdmrconf/openrtx_interface.hh
/usr/include/libdmrconf/openuv380.hh
/usr/include/libdmrconf/openuv380_callsigndb.hh
/usr/include/libdmrconf/openuv380_codeplug.hh
/usr/include/libdmrconf/orbitalelementsdatabase.hh
/usr/include/libdmrconf/radio.hh
/usr/include/libdmrconf/radioddity_codeplug.hh
/usr/include/libdmrconf/radioddity_extensions.hh
/usr/include/libdmrconf/radioddity_interface.hh
/usr/include/libdmrconf/radioddity_radio.hh
/usr/include/libdmrconf/radioid.hh
/usr/include/libdmrconf/radioinfo.hh
/usr/include/libdmrconf/radiointerface.hh
/usr/include/libdmrconf/radiolimits.hh
/usr/include/libdmrconf/radiosettings.hh
/usr/include/libdmrconf/ranges.hh
/usr/include/libdmrconf/rd5r.hh
/usr/include/libdmrconf/rd5r_codeplug.hh
/usr/include/libdmrconf/rd5r_filereader.hh
/usr/include/libdmrconf/rd5r_limits.hh
/usr/include/libdmrconf/roamingchannel.hh
/usr/include/libdmrconf/roamingzone.hh
/usr/include/libdmrconf/rxgrouplist.hh
/usr/include/libdmrconf/satellitedatabase.hh
/usr/include/libdmrconf/scanlist.hh
/usr/include/libdmrconf/signaling.hh
/usr/include/libdmrconf/smsextension.hh
/usr/include/libdmrconf/talkgroupdatabase.hh
/usr/include/libdmrconf/transponderdatabase.hh
/usr/include/libdmrconf/tyt_callsigndb.hh
/usr/include/libdmrconf/tyt_codeplug.hh
/usr/include/libdmrconf/tyt_extensions.hh
/usr/include/libdmrconf/tyt_interface.hh
/usr/include/libdmrconf/tyt_radio.hh
/usr/include/libdmrconf/usbdevice.hh
/usr/include/libdmrconf/usbserial.hh
/usr/include/libdmrconf/userdatabase.hh
/usr/include/libdmrconf/utils.hh
/usr/include/libdmrconf/uv390.hh
/usr/include/libdmrconf/uv390_callsigndb.hh
/usr/include/libdmrconf/uv390_codeplug.hh
/usr/include/libdmrconf/uv390_filereader.hh
/usr/include/libdmrconf/uv390_limits.hh
/usr/include/libdmrconf/visitor.hh
/usr/include/libdmrconf/zone.hh
/usr/lib64/libdmrconf.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdmrconf.so.0
/usr/lib64/libdmrconf.so.0.12.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qdmr/31a3d460bb3c7d98845187c716a30db81c44b615
